import { Sound, TrendHistory } from './types';

export const MOCK_SOUNDS: Sound[] = [
  {
    id: 'yt-1',
    platform: 'youtube',
    sound_url: 'https://www.youtube.com/watch?v=dQw4w9WgXcQ',
    embed_url: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    title: 'Big Stepper',
    artist: 'Kendrick Lamar',
    duration: 32,
    trend_score: 94.7,
    velocity_score: 88.2,
    reuse_count: 184200,
    category: 'Hype',
    mood: 'Dark',
    tags: ['rap', 'flex', 'viral', 'westcoast'],
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'yt-2',
    platform: 'youtube',
    sound_url: 'https://www.youtube.com/watch?v=SlPhMPnQ58k',
    embed_url: 'https://www.youtube.com/embed/SlPhMPnQ58k',
    title: 'Harleys in Hawaii',
    artist: 'Katy Perry',
    duration: 28,
    trend_score: 87.3,
    velocity_score: 72.5,
    reuse_count: 122000,
    category: 'Chill',
    mood: 'Chill',
    tags: ['chill', 'travel', 'vibes', 'summer'],
    created_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'yt-3',
    platform: 'youtube',
    sound_url: 'https://www.youtube.com/watch?v=2Vv-BfVoq4g',
    embed_url: 'https://www.youtube.com/embed/2Vv-BfVoq4g',
    title: 'Perfect',
    artist: 'Ed Sheeran',
    duration: 30,
    trend_score: 81.5,
    velocity_score: 65.0,
    reuse_count: 98400,
    category: 'Cinematic',
    mood: 'Emotional',
    tags: ['romantic', 'wedding', 'emotional', 'pop'],
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'yt-4',
    platform: 'youtube',
    sound_url: 'https://www.youtube.com/watch?v=nfWlot6h_JM',
    embed_url: 'https://www.youtube.com/embed/nfWlot6h_JM',
    title: 'Shake It Off',
    artist: 'Taylor Swift',
    duration: 24,
    trend_score: 79.1,
    velocity_score: 91.3,
    reuse_count: 87600,
    category: 'Meme',
    mood: 'Funny',
    tags: ['meme', 'dance', 'pop', 'vibes'],
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'yt-5',
    platform: 'youtube',
    sound_url: 'https://www.youtube.com/watch?v=JGwWNGJdvx8',
    embed_url: 'https://www.youtube.com/embed/JGwWNGJdvx8',
    title: 'Shape of You',
    artist: 'Ed Sheeran',
    duration: 27,
    trend_score: 75.8,
    velocity_score: 58.4,
    reuse_count: 76200,
    category: 'Hype',
    mood: 'Energetic',
    tags: ['pop', 'dance', 'club', 'viral'],
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'yt-6',
    platform: 'youtube',
    sound_url: 'https://www.youtube.com/watch?v=OPf0YbXqDm0',
    embed_url: 'https://www.youtube.com/embed/OPf0YbXqDm0',
    title: 'Mark Spears',
    artist: 'NBA YoungBoy',
    duration: 20,
    trend_score: 91.2,
    velocity_score: 95.6,
    reuse_count: 163400,
    category: 'NBA',
    mood: 'Hype',
    tags: ['nba', 'basketball', 'highlights', 'hype'],
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'yt-7',
    platform: 'youtube',
    sound_url: 'https://www.youtube.com/watch?v=H5v3kku4y6Q',
    embed_url: 'https://www.youtube.com/embed/H5v3kku4y6Q',
    title: 'Gimme! Gimme! Gimme!',
    artist: 'ABBA',
    duration: 30,
    trend_score: 68.9,
    velocity_score: 82.1,
    reuse_count: 54800,
    category: 'Meme',
    mood: 'Funny',
    tags: ['meme', 'retro', 'dance', 'throwback'],
    created_at: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'yt-8',
    platform: 'youtube',
    sound_url: 'https://www.youtube.com/watch?v=fRh_vgS2dFE',
    embed_url: 'https://www.youtube.com/embed/fRh_vgS2dFE',
    title: 'Sorry',
    artist: 'Justin Bieber',
    duration: 25,
    trend_score: 62.4,
    velocity_score: 44.7,
    reuse_count: 43100,
    category: 'Viral',
    mood: 'Energetic',
    tags: ['pop', 'dance', 'viral', 'comeback'],
    created_at: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'yt-9',
    platform: 'youtube',
    sound_url: 'https://www.youtube.com/watch?v=YqeW9_5kURI',
    embed_url: 'https://www.youtube.com/embed/YqeW9_5kURI',
    title: 'Superhero',
    artist: 'Metro Boomin',
    duration: 18,
    trend_score: 88.0,
    velocity_score: 90.4,
    reuse_count: 141000,
    category: 'NBA',
    mood: 'Dramatic',
    tags: ['nba', 'cinematic', 'hype', 'superhero'],
    created_at: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'yt-10',
    platform: 'youtube',
    sound_url: 'https://www.youtube.com/watch?v=XS088Opj9o0',
    embed_url: 'https://www.youtube.com/embed/XS088Opj9o0',
    title: 'Flowers',
    artist: 'Miley Cyrus',
    duration: 23,
    trend_score: 73.6,
    velocity_score: 55.9,
    reuse_count: 68900,
    category: 'Chill',
    mood: 'Emotional',
    tags: ['pop', 'empowerment', 'viral', 'summer'],
    created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'yt-11',
    platform: 'youtube',
    sound_url: 'https://www.youtube.com/watch?v=y6Sxv-sUYtM',
    embed_url: 'https://www.youtube.com/embed/y6Sxv-sUYtM',
    title: 'Bohemian Rhapsody',
    artist: 'Queen',
    duration: 30,
    trend_score: 65.2,
    velocity_score: 76.3,
    reuse_count: 51200,
    category: 'Cinematic',
    mood: 'Dramatic',
    tags: ['classic', 'cinematic', 'rock', 'drama'],
    created_at: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'yt-12',
    platform: 'youtube',
    sound_url: 'https://www.youtube.com/watch?v=kffacxfA7G4',
    embed_url: 'https://www.youtube.com/embed/kffacxfA7G4',
    title: 'Baby Shark',
    artist: 'Pinkfong',
    duration: 15,
    trend_score: 55.8,
    velocity_score: 33.2,
    reuse_count: 31000,
    category: 'Meme',
    mood: 'Funny',
    tags: ['meme', 'viral', 'kids', 'funny'],
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export function generateTrendHistory(soundId: string): TrendHistory[] {
  const sound = MOCK_SOUNDS.find(s => s.id === soundId);
  if (!sound) return [];

  const points = 14; // 14 days of history
  const history: TrendHistory[] = [];
  const baseViews = sound.reuse_count * 8;
  const baseUses = sound.reuse_count;

  for (let i = points; i >= 0; i--) {
    const dayFactor = (points - i) / points;
    const randomVariance = 0.85 + Math.random() * 0.3;
    const growthFactor = 1 + dayFactor * (sound.velocity_score / 100) * 2;

    const views = Math.floor(baseViews * dayFactor * randomVariance * growthFactor * 0.15);
    const uses = Math.floor(baseUses * dayFactor * randomVariance * growthFactor * 0.1);
    const growth_rate = i === points ? 0 : ((views - (history[history.length - 1]?.views ?? views * 0.8)) / Math.max(history[history.length - 1]?.views ?? 1, 1)) * 100;

    history.push({
      id: i,
      sound_id: soundId,
      timestamp: new Date(Date.now() - i * 24 * 60 * 60 * 1000).toISOString(),
      views,
      uses,
      growth_rate: Math.round(growth_rate * 10) / 10,
    });
  }

  return history;
}
